language: cpp
compiler:
  - gcc
  - clang
install:
  - cd src/ted/
  - sudo apt-get update
  - sudo apt-get -y install g++ libglu1-mesa-dev libopenal-dev ant
  - sudo apt-get install qtcreator libqt4-dev libqtwebkit-dev qt4-qmake
script:
  - qmake -project
  - qmake ted.pro
  - make
os:
  - linux
  - osx
